"use client";
import Image from "next/image";
import { useMemo, useState } from "react";
import { categories, type Category, type MenuItem } from "@/data/menu";
import { filterMenu, formatPrice, type SortOption } from "@/lib/catalog";
export function MenuCatalog({ items }: { items: MenuItem[] }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState<Category>("Todos"); const [sort, setSort] = useState<SortOption>("featured");
  const results = useMemo(() => filterMenu(items, query, category, sort), [items, query, category, sort]);
  return <div className="catalog"><div className="controls"><label className="search"><span className="sr-only">Buscar no cardápio</span><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busque por um sabor" type="search" /></label><label className="sort"><span className="sr-only">Ordenar opções</span><select value={sort} onChange={(event) => setSort(event.target.value as SortOption)}><option value="featured">Mais relevantes</option><option value="price-asc">Menor preço</option><option value="price-desc">Maior preço</option><option value="name">De A a Z</option></select></label></div><div className="filters" aria-label="Filtrar por categoria">{categories.map((item) => <button key={item} className={category === item ? "filter active" : "filter"} onClick={() => setCategory(item)}>{item}</button>)}</div><p className="results" aria-live="polite">{results.length} {results.length === 1 ? "opção encontrada" : "opções encontradas"}</p>{results.length ? <div className="products">{results.map((item) => <article className="product-card" key={item.id}><div className="product-image"><Image src={item.image} alt={item.name} fill sizes="(max-width: 700px) 100vw, (max-width: 1050px) 50vw, 33vw" /></div><div className="product-content"><span className="category">{item.category}</span><h3>{item.name}</h3><p>{item.description}</p><strong>{formatPrice(item.price)}</strong></div></article>)}</div> : <div className="empty"><span aria-hidden="true">⌕</span><h3>Nada por aqui ainda</h3><p>Tente outro termo ou remova os filtros para ver o cardápio completo.</p><button onClick={() => { setQuery(""); setCategory("Todos"); }}>Limpar filtros</button></div>}</div>;
}
